// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {"Study" | "Rest" | "AFK"} PomoType
	* @property {"Study"} Study
	* @property {"Rest"} Rest
	* @property {"AFK"} AFK
	*/
