// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  print to stdout instead of the in terminal.
	 * @param {string} text
	 * @returns {Promise<void>}
	 */
	print: (text) => __TAURI_INVOKE("print", { text }),
	/**
	 *  This is a default function that came with tauri
	 *  It will be removed soon
	 * @param {string} name
	 * @returns {Promise<string>}
	 */
	greet: (name) => __TAURI_INVOKE("greet", { name }),
	/**
	 *  Create a timer, it returns the index of the timer.
	 * @returns {Promise<number>}
	 */
	createTimer: () => __TAURI_INVOKE("create_timer"),
	/**
	 *  Get a timers time from its current position in the index.
	 * @param {number} index
	 * @returns {Promise<number>}
	 */
	getTimer: (index) => __TAURI_INVOKE("get_timer", { index }),
	/**
	 *  Host a connection, this will error if you try to run this/join twice.
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	host: (room) => typedError(__TAURI_INVOKE("host", { room })),
	/**
	 *  Join a connection, you can string both the top and the bottom to join the host
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	join: (room) => typedError(__TAURI_INVOKE("join", { room })),
	/**
	 *  This is to send a connection, both host and join can send one. plain text.
	 * @param {string} message
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	sendmessage: (message) => typedError(__TAURI_INVOKE("sendmessage", { message })),
	/**
	 *  This is to receive the message, it will return the string or empty if there wasnt any messasges
	 * @returns {Promise<string | null>}
	 */
	receivemessage: () => __TAURI_INVOKE("receivemessage"),
};

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}
