// This file has been generated by Tauri Specta. Do not edit this file manually.

/**
 * @typedef {import("./pomotimer_lib/discord")} pomotimer_lib$discord
 * @typedef {import("./pomotimer_lib/events")} pomotimer_lib$events
 */

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  print to stdout instead of the in terminal.
	 * @param {string} text
	 * @returns {Promise<void>}
	 */
	print: (text) => __TAURI_INVOKE("print", { text }),
	/**
	 *  This is a default function that came with tauri
	 *  It will be removed soon
	 * @param {string} name
	 * @returns {Promise<string>}
	 */
	greet: (name) => __TAURI_INVOKE("greet", { name }),
	/**
	 *  Create a timer, it returns the index of the timer.
	 * @returns {Promise<number>}
	 */
	createTimer: () => __TAURI_INVOKE("create_timer"),
	/**
	 *  Get a timers time from its current position in the index.
	 * @param {number} index
	 * @returns {Promise<number>}
	 */
	getTimer: (index) => __TAURI_INVOKE("get_timer", { index }),
	/**
	 *  Host a connection, this will error if you try to run this/join twice.
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	host: (room) => typedError(__TAURI_INVOKE("host", { room })),
	/**
	 *  Join a connection, you can string both the top and the bottom to join the host
	 * @param {string} room
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	join: (room) => typedError(__TAURI_INVOKE("join", { room })),
	/**
	 *  This is to send a connection, both host and join can send one. plain text.
	 * @param {string} message
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	sendmessage: (message) => typedError(__TAURI_INVOKE("sendmessage", { message })),
	/**
	 *  This is to receive the message, it will return the string or null if there wasnt any messasges
	 *  This will return the oldest unread message.
	 * @returns {Promise<string | null>}
	 */
	receivemessage: () => __TAURI_INVOKE("receivemessage"),
	/**
	 *  Set discord status.
	 *  Name of activity, e.g, maths, science and stuff
	 *  Time in seconds for completion
	 *  Pomotype, check bindings for all possible pomotypes (will err in console if invalid)
	 * @param {pomotimer_lib$discord.PomoType} pomotype
	 * @returns {Promise<{ status: "ok"; data: null } | { status: "error"; error: string }>}
	 */
	setStatus: (pomotype) => typedError(__TAURI_INVOKE("set_status", { pomotype })),
};

/** Events */
export const events = {
	/** @type {ReturnType<typeof makeEvent<pomotimer_lib$events.JoinEvent>>} */
	joinEvent: makeEvent("join-event"),
	/** @type {ReturnType<typeof makeEvent<pomotimer_lib$events.MessageEvent>>} */
	messageEvent: makeEvent("message-event"),
};

/* Tauri Specta runtime */
/**
  * @template T
  * @template E
  * @param {Promise<T>} result
  * @returns {Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>}
  */
async function typedError(result) {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e };
    }
}

/**
 * @template T
 * @param {string} name
 * @param {(payload: T) => unknown} [serialize]
 * @param {(payload: any) => T} [deserialize]
 */
function makeEvent(name, serialize, deserialize) {
    const mapEvent = (cb) => (event) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload) => serialize ? serialize(payload) : payload;

    const base = {
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => __TAURI_EVENT.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => __TAURI_EVENT.emit(name, mapPayload(payload)),
    };

    /** @param {import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window} target */
    const fn = (target) => ({
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        listen: (cb) => target.listen(name, mapEvent(cb)),
        /** @param {__TAURI_EVENT.EventCallback<T>} cb */
        once: (cb) => target.once(name, mapEvent(cb)),
        /** @param {T} payload */
        emit: (payload) => target.emit(name, mapPayload(payload)),
    });

    return Object.assign(fn, base);
}
