// This file has been generated by Tauri Specta. Do not edit this file manually.
/**
	* @typedef {"Rest" | "Study" | "Afk"} TimerState
	* @property {"Rest"} Rest
	* @property {"Study"} Study
	* @property {"Afk"} Afk
	*/
